"""empty message

Revision ID: 2ebb7a7a3aa6
Revises: 8b233f3d9422
Create Date: 2017-12-08 11:27:55.987678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebb7a7a3aa6'
down_revision = '8b233f3d9422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battle_results', 'elapsed_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battle_results', 'elapsed_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
