"""empty message

Revision ID: 553f26780024
Revises: b7ca13a2df8c
Create Date: 2017-12-04 12:23:26.406074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553f26780024'
down_revision = 'b7ca13a2df8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_results')
    # ### end Alembic commands ###
