"""empty message

Revision ID: 8b233f3d9422
Revises: 35d79da81783
Create Date: 2017-12-08 09:59:25.621221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b233f3d9422'
down_revision = '35d79da81783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_results', sa.Column('elapsed_time', sa.Integer(), nullable=False))
    op.drop_column('battle_results', 'elpased_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_results', sa.Column('elpased_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('battle_results', 'elapsed_time')
    # ### end Alembic commands ###
