"""empty message

Revision ID: 9050045bf92b
Revises: d76522e599df
Create Date: 2017-12-06 20:45:15.973320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9050045bf92b'
down_revision = 'd76522e599df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('udemae', sa.JSON(), nullable=True),
    sa.Column('star_rank', sa.Integer(), nullable=True),
    sa.Column('weapon_paint_point', sa.Integer(), nullable=True),
    sa.Column('game_paint_point', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('kill_count', sa.Integer(), nullable=True),
    sa.Column('assist_count', sa.Integer(), nullable=True),
    sa.Column('death_count', sa.Integer(), nullable=True),
    sa.Column('special_count', sa.Integer(), nullable=True),
    sa.Column('sort_score', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('game_mode_id', sa.Integer(), nullable=False),
    sa.Column('player_battle_member_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('elpased_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('my_team_result_id', sa.Integer(), nullable=False),
    sa.Column('other_team_result_id', sa.Integer(), nullable=False),
    sa.Column('estimate_gachi_power', sa.Integer(), nullable=True),
    sa.Column('my_team_count', sa.Integer(), nullable=True),
    sa.Column('other_team_count', sa.Integer(), nullable=True),
    sa.Column('league_point', sa.Float(), nullable=True),
    sa.Column('max_league_point', sa.Integer(), nullable=True),
    sa.Column('my_estimate_league_point', sa.Integer(), nullable=True),
    sa.Column('other_estimate_league_point', sa.Integer(), nullable=True),
    sa.Column('win_meter', sa.Integer(), nullable=True),
    sa.Column('my_team_percentage', sa.Float(), nullable=True),
    sa.Column('other_team_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_mode_id'], ['game_modes.id'], ),
    sa.ForeignKeyConstraint(['my_team_result_id'], ['team_results.id'], ),
    sa.ForeignKeyConstraint(['other_team_result_id'], ['team_results.id'], ),
    sa.ForeignKeyConstraint(['player_battle_member_id'], ['battle_members.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_result_members',
    sa.Column('battle_result_id', sa.Integer(), nullable=True),
    sa.Column('battle_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_member_id'], ['battle_members.id'], ),
    sa.ForeignKeyConstraint(['battle_result_id'], ['battle_results.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle_result_members')
    op.drop_table('battle_results')
    op.drop_table('battle_members')
    # ### end Alembic commands ###
